apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iacdharma-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "200"
    nginx.ingress.kubernetes.io/limit-connections: "100"
spec:
  tls:
  - hosts:
    - iacdharma.com
    - www.iacdharma.com
    - api.iacdharma.com
    secretName: iacdharma-prod-tls-cert
  rules:
  - host: iacdharma.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: www.iacdharma.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: api.iacdharma.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 3000
